// GENERATED CODE — DO NOT EDIT BY HAND
// Generated by codegen/generate.dart from schemas/forum.json
// ignore_for_file: lines_longer_than_80_chars

import '../core/base_client.dart';

/// Lolzteam Forum API client.
///
/// Auto-generated from OpenAPI schema.
class ForumClient extends BaseClient {
  static const _baseUrl = 'https://api.lzt.market';

  ForumClient({
    required super.token,
    super.proxy,
    super.maxRetries,
    super.retryDelay,
  });

  @override
  Uri buildUri(String path, Map<String, String>? params) =>
      Uri.parse('$_baseUrl$path').replace(queryParameters: params);

  /// POST /oauth/token — Get Access Token
  ///
  /// Obtain an access token using various grant types. Supports the following grant types: -
  /// Client Credentials - Authorization Code
  Future<Map<String, dynamic>> oauthToken({
    Map<String, dynamic>? body,
  }) {
    return post('/oauth/token', body: body);
  }

  /// GET /css — Get CSS
  ///
  /// Gets css rulesets for requested selectors.
  ///
  /// [css] The names or identifiers of the CSS selectors to retrieve.
  Future<Map<String, dynamic>> assetsCss({
    List<String>? css,
  }) {
    final _queryArgs = <String, String>{
      if (css != null) 'css': css!.join(','),
    };
    return get('/css', params: _queryArgs);
  }

  /// GET /categories — Get Categories
  ///
  /// List of all categories in the system. Required scopes: + **read**
  ///
  /// [parentCategoryId] Id of parent category. If exists, filter categories that are direct children of that category.
  ///
  /// [parentForumId] Id of parent forum. If exists, filter categories that are direct children of that forum.
  ///
  /// [order] Ordering of categories.
  Future<Map<String, dynamic>> categoriesList({
    int? parentCategoryId,
    int? parentForumId,
    String? order,
  }) {
    final _queryArgs = <String, String>{
      if (parentCategoryId != null) 'parent_category_id': parentCategoryId!.toString(),
      if (parentForumId != null) 'parent_forum_id': parentForumId!.toString(),
      if (order != null) 'order': order!,
    };
    return get('/categories', params: _queryArgs);
  }

  /// GET /categories/{category_id} — Get Category
  ///
  /// Detail information of a category. Required scopes: + **read**
  ///
  /// [categoryId] Id of category.
  Future<Map<String, dynamic>> categoriesGet({
    required int categoryId,
  }) {
    return get('/categories/$categoryId');
  }

  /// GET /forums — Get Forums
  ///
  /// List of all forums in the system. Required scopes: + **read**
  ///
  /// [parentCategoryId] Id of parent category. If exists, filter forums that are direct children of that category.
  ///
  /// [parentForumId] Id of parent forum. If exists, filter forums that are direct children of that forum.
  ///
  /// [order] Ordering of forums.
  Future<Map<String, dynamic>> forumsList({
    int? parentCategoryId,
    int? parentForumId,
    String? order,
  }) {
    final _queryArgs = <String, String>{
      if (parentCategoryId != null) 'parent_category_id': parentCategoryId!.toString(),
      if (parentForumId != null) 'parent_forum_id': parentForumId!.toString(),
      if (order != null) 'order': order!,
    };
    return get('/forums', params: _queryArgs);
  }

  /// GET /forums/grouped — Get Forums Tree
  ///
  /// Returns grouped forums. Required scopes: + **read**
  Future<Map<String, dynamic>> forumsGrouped() {
    return get('/forums/grouped');
  }

  /// GET /forums/{forum_id} — Get Forum
  ///
  /// Detail information of a forum. Required scopes: + **read**
  ///
  /// [forumId] Id of forum.
  Future<Map<String, dynamic>> forumsGet({
    required int forumId,
  }) {
    return get('/forums/$forumId');
  }

  /// GET /forums/{forum_id}/followers — Get Followers
  ///
  /// List of a forum's followers. For privacy reason, only the current user will be included
  /// in the list (if the user follows the specified forum). Required scopes: + **read**
  ///
  /// [forumId] Id of forum.
  Future<Map<String, dynamic>> forumsFollowers({
    required int forumId,
  }) {
    return get('/forums/$forumId/followers');
  }

  /// POST /forums/{forum_id}/followers — Follow Forum
  ///
  /// Follow a forum. Required scopes: + **post**
  ///
  /// [forumId] Id of forum.
  ///
  /// [post_] Whether to receive notification for post.
  ///
  /// [alert] Whether to receive notification as alert.
  ///
  /// [email] Whether to receive notification as email.
  ///
  /// [prefixIds] Prefix ids.
  ///
  /// [minimalContestAmount] Minimal contest amount. (Only for 766 forumId)
  Future<Map<String, dynamic>> forumsFollow({
    required int forumId,
    bool? post_,
    bool? alert,
    bool? email,
    List<int>? prefixIds,
    int? minimalContestAmount,
  }) {
    final bodyMap = <String, dynamic>{
        if (post_ != null) 'post': post_,
        if (alert != null) 'alert': alert,
        if (email != null) 'email': email,
        if (prefixIds != null) 'prefix_ids': prefixIds,
        if (minimalContestAmount != null) 'minimal_contest_amount': minimalContestAmount,
    };
    return post('/forums/$forumId/followers', body: bodyMap);
  }

  /// DELETE /forums/{forum_id}/followers — Unfollow Forum
  ///
  /// Unfollow a forum. Required scopes: + **post**
  ///
  /// [forumId] Id of forum.
  Future<Map<String, dynamic>> forumsUnfollow({
    required int forumId,
  }) {
    return delete('/forums/$forumId/followers');
  }

  /// GET /forums/followed — Get Followed Forums
  ///
  /// List of followed forums by current user. Required scopes: + **read**
  ///
  /// [total] If included in the request, only the forum count is returned as **forums_total**.
  Future<Map<String, dynamic>> forumsFollowed({
    bool? total,
  }) {
    final _queryArgs = <String, String>{
      if (total != null) 'total': total!.toString(),
    };
    return get('/forums/followed', params: _queryArgs);
  }

  /// GET /forums/feed/options — Get Feed Options
  ///
  /// Returns available options for the forums feed. Required scopes: + **read**
  Future<Map<String, dynamic>> forumsGetfeedoptions() {
    return get('/forums/feed/options');
  }

  /// PUT /forums/feed/options — Edit Feed Options
  ///
  /// Edit feed options. Required scopes: + **post**
  ///
  /// [nodeIds] Array of forum ids to exclude from the feed.
  ///
  /// [keywords] List of keywords to exclude specific threads from the feed.
  Future<Map<String, dynamic>> forumsEditfeedoptions({
    List<int>? nodeIds,
    List<String>? keywords,
  }) {
    final bodyMap = <String, dynamic>{
        if (nodeIds != null) 'node_ids': nodeIds,
        if (keywords != null) 'keywords': keywords,
    };
    return put('/forums/feed/options', body: bodyMap);
  }

  /// GET /link-forums — Get Links Forum
  ///
  /// List of all link forums. Required scopes: + **read**
  Future<Map<String, dynamic>> linksList() {
    return get('/link-forums');
  }

  /// GET /link-forums/{link_id} — Get Link Forum
  ///
  /// Detail information of a link forum. Required scopes: + **read**
  ///
  /// [linkId] Id of link forum.
  Future<Map<String, dynamic>> linksGet({
    required int linkId,
  }) {
    return get('/link-forums/$linkId');
  }

  /// GET /pages — Get Pages
  ///
  /// List of all pages in the system. Required scopes: + **read**
  ///
  /// [parentPageId] Id of parent page. If exists, filter pages that are direct children of that page.
  ///
  /// [order] Ordering of pages.
  Future<Map<String, dynamic>> pagesList({
    int? parentPageId,
    String? order,
  }) {
    final _queryArgs = <String, String>{
      if (parentPageId != null) 'parent_page_id': parentPageId!.toString(),
      if (order != null) 'order': order!,
    };
    return get('/pages', params: _queryArgs);
  }

  /// GET /pages/{page_id} — Get Page
  ///
  /// Detail information of a page. Required scopes: + **read**
  ///
  /// [pageId] Id of page.
  Future<Map<String, dynamic>> pagesGet({
    required int pageId,
  }) {
    return get('/pages/$pageId');
  }

  /// GET /navigation — Get Navigation
  ///
  /// List of navigation elements within the system. Required scopes: + **read**
  ///
  /// [parent] Id of parent element. If exists, filter elements that are direct children of that element.
  Future<Map<String, dynamic>> navigationList({
    int? parent,
  }) {
    final _queryArgs = <String, String>{
      if (parent != null) 'parent': parent!.toString(),
    };
    return get('/navigation', params: _queryArgs);
  }

  /// GET /threads — Get Threads
  ///
  /// List of threads in a forum (with pagination). Required scopes: + **read**
  ///
  /// [forumId] Id of the containing forum.
  ///
  /// [tab] Tab to get threads from.
  ///
  /// [state] Thread state. Works only if **forum_id** is set.
  ///
  /// [period] Filter to get only threads created within the selected period. Works only if **forum_id** is set.
  ///
  /// [title] Thread title.
  ///
  /// [titleOnly] Search only in titles.
  ///
  /// [creatorUserId] Filter to get only threads created by the specified user.
  ///
  /// [sticky] Filter to get only sticky or non-sticky threads. By default, all threads will be included and sticky ones will be at the top of the result on the first page. In mixed mode, sticky threads are not counted towards **threads_total** and does not affect pagination.
  ///
  /// [prefixIds] Filter to get only threads with the specified prefix.
  ///
  /// [prefixIdsNot] Filter to get only threads without the specified prefix.
  ///
  /// [threadTagId] Filter to get only threads with the specified tag.
  ///
  /// [page] Page number of threads.
  ///
  /// [limit] Number of threads in a page.
  ///
  /// [order] Ordering of threads.
  ///
  /// [direction] Direction of threads ordering.
  ///
  /// [threadCreateDate] Filter threads by creation date. Only works with 'thread_create_date' and 'thread_create_date_reverse' ordering.
  ///
  /// [threadUpdateDate] Filter threads by update date. Only works with 'thread_update_date' and 'thread_update_date_reverse' ordering.
  ///
  /// [fieldsInclude] List of fields to include.
  Future<Map<String, dynamic>> threadsList({
    int? forumId,
    String? tab,
    String? state,
    String? period,
    String? title,
    bool? titleOnly,
    int? creatorUserId,
    bool? sticky,
    List<int>? prefixIds,
    List<int>? prefixIdsNot,
    int? threadTagId,
    int? page,
    int? limit,
    String? order,
    String? direction,
    int? threadCreateDate,
    int? threadUpdateDate,
    List<String>? fieldsInclude,
  }) {
    final _queryArgs = <String, String>{
      if (forumId != null) 'forum_id': forumId!.toString(),
      if (tab != null) 'tab': tab!,
      if (state != null) 'state': state!,
      if (period != null) 'period': period!,
      if (title != null) 'title': title!,
      if (titleOnly != null) 'title_only': titleOnly!.toString(),
      if (creatorUserId != null) 'creator_user_id': creatorUserId!.toString(),
      if (sticky != null) 'sticky': sticky!.toString(),
      if (prefixIds != null) 'prefix_ids[]': prefixIds!.join(','),
      if (prefixIdsNot != null) 'prefix_ids_not[]': prefixIdsNot!.join(','),
      if (threadTagId != null) 'thread_tag_id': threadTagId!.toString(),
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
      if (order != null) 'order': order!,
      if (direction != null) 'direction': direction!,
      if (threadCreateDate != null) 'thread_create_date': threadCreateDate!.toString(),
      if (threadUpdateDate != null) 'thread_update_date': threadUpdateDate!.toString(),
      if (fieldsInclude != null) 'fields_include': fieldsInclude!.join(','),
    };
    return get('/threads', params: _queryArgs);
  }

  /// POST /threads — Create Thread
  ///
  /// Create a new thread. Required scopes: + **post**
  ///
  /// [postBody] Content of the new thread.
  ///
  /// [forumId] Id of the target forum.
  ///
  /// [title] Thread title. Can be skipped if **title_en** set.
  ///
  /// [titleEn] Thread english title. Can be skipped if **title** set.
  ///
  /// [prefixId] Prefix ids.
  ///
  /// [tags] Thread tags.
  ///
  /// [hideContacts] Hide contacts.
  ///
  /// [allowAskHiddenContent] Allow ask hidden content.
  ///
  /// [replyGroup] Allow to reply only users with chosen or higher group.
  ///
  /// [commentIgnoreGroup] Allow commenting if user can't post in thread.
  ///
  /// [dontAlertFollowers] Don't alert followers about thread creation.
  ///
  /// [scheduleDate] Date to schedule thread creation (format: `DD-MM-YYYY`).
  ///
  /// [scheduleTime] Time to schedule thread creation (format: `HH:MM`).
  ///
  /// [watchThreadState] Watch thread state.
  ///
  /// [watchThread] Receive forum notifications of new posts in this thread.
  ///
  /// [watchThreadEmail] Receive email notifications of new posts in this thread.
  Future<Map<String, dynamic>> threadsCreate({
    required String postBody,
    required int forumId,
    String? title,
    String? titleEn,
    List<int>? prefixId,
    List<String>? tags,
    bool? hideContacts,
    bool? allowAskHiddenContent,
    int? replyGroup,
    bool? commentIgnoreGroup,
    bool? dontAlertFollowers,
    String? scheduleDate,
    String? scheduleTime,
    bool? watchThreadState,
    bool? watchThread,
    bool? watchThreadEmail,
  }) {
    final bodyMap = <String, dynamic>{
        'post_body': postBody,
        'forum_id': forumId,
        if (title != null) 'title': title,
        if (titleEn != null) 'title_en': titleEn,
        if (prefixId != null) 'prefix_id': prefixId,
        if (tags != null) 'tags': tags,
        if (hideContacts != null) 'hide_contacts': hideContacts,
        if (allowAskHiddenContent != null) 'allow_ask_hidden_content': allowAskHiddenContent,
        if (replyGroup != null) 'reply_group': replyGroup,
        if (commentIgnoreGroup != null) 'comment_ignore_group': commentIgnoreGroup,
        if (dontAlertFollowers != null) 'dont_alert_followers': dontAlertFollowers,
        if (scheduleDate != null) 'schedule_date': scheduleDate,
        if (scheduleTime != null) 'schedule_time': scheduleTime,
        if (watchThreadState != null) 'watch_thread_state': watchThreadState,
        if (watchThread != null) 'watch_thread': watchThread,
        if (watchThreadEmail != null) 'watch_thread_email': watchThreadEmail,
    };
    return post('/threads', body: bodyMap);
  }

  /// POST /contests — Create Contest
  ///
  /// Create a new contest. Required scopes: + **post**
  ///
  /// [postBody] Content of the new contest.
  ///
  /// [title] Thread title. Can be skipped if **title_en** set.
  ///
  /// [titleEn] Thread english title. Can be skipped if **title** set.
  ///
  /// [contestType] Contest type.
  ///
  /// [lengthValue] Giveaway duration value. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
  ///
  /// [lengthOption] Giveaway duration type. The maximum duration is 3 days. Required if **contest_type** is **by_finish_date**.
  ///
  /// [prizeType] Prize type.
  ///
  /// [countWinners] Winner count (prize count). Optional if **prize_type** is **money**.
  ///
  /// [prizeDataMoney] How much money will each winner receive. Optional if **prize_type** is **money**.
  ///
  /// [isMoneyPlaces] Enable the distribution of money prizes by places. Optional if **prize_type** is **money**.
  ///
  /// [prizeDataPlaces] How much money will receive each place. Required if **is_money_places** is **1**.
  ///
  /// [prizeDataUpgrade] Which upgrade will each winner receive. Required if **prize_type** is **upgrades**.
  ///
  /// [requireLikeCount] Sympathies for this week.
  ///
  /// [requireTotalLikeCount] Sympathies for all time.
  ///
  /// [secretAnswer] Secret answer of your account.
  ///
  /// [tags] Thread tags.
  ///
  /// [replyGroup] Allow to reply only users with chosen or higher group.
  ///
  /// [commentIgnoreGroup] Allow commenting if user can't post in thread.
  ///
  /// [dontAlertFollowers] Don't alert followers about thread creation.
  ///
  /// [hideContacts] Hide contacts.
  ///
  /// [allowAskHiddenContent] Allow ask hidden content.
  ///
  /// [scheduleDate] Date to schedule thread creation (format: `DD-MM-YYYY`).
  ///
  /// [scheduleTime] Time to schedule thread creation (format: `HH:MM`).
  ///
  /// [watchThreadState] Watch thread state.
  ///
  /// [watchThread] Receive forum notifications of new posts in this thread.
  ///
  /// [watchThreadEmail] Receive email notifications of new posts in this thread.
  Future<Map<String, dynamic>> threadsCreatecontest({
    required String postBody,
    required String contestType,
    required String prizeType,
    required int requireLikeCount,
    required int requireTotalLikeCount,
    String? title,
    String? titleEn,
    int? lengthValue,
    String? lengthOption,
    int? countWinners,
    num? prizeDataMoney,
    bool? isMoneyPlaces,
    List<num>? prizeDataPlaces,
    int? prizeDataUpgrade,
    String? secretAnswer,
    List<String>? tags,
    int? replyGroup,
    bool? commentIgnoreGroup,
    bool? dontAlertFollowers,
    bool? hideContacts,
    bool? allowAskHiddenContent,
    String? scheduleDate,
    String? scheduleTime,
    bool? watchThreadState,
    bool? watchThread,
    bool? watchThreadEmail,
  }) {
    final bodyMap = <String, dynamic>{
        'post_body': postBody,
        if (title != null) 'title': title,
        if (titleEn != null) 'title_en': titleEn,
        'contest_type': contestType,
        if (lengthValue != null) 'length_value': lengthValue,
        if (lengthOption != null) 'length_option': lengthOption,
        'prize_type': prizeType,
        if (countWinners != null) 'count_winners': countWinners,
        if (prizeDataMoney != null) 'prize_data_money': prizeDataMoney,
        if (isMoneyPlaces != null) 'is_money_places': isMoneyPlaces,
        if (prizeDataPlaces != null) 'prize_data_places': prizeDataPlaces,
        if (prizeDataUpgrade != null) 'prize_data_upgrade': prizeDataUpgrade,
        'require_like_count': requireLikeCount,
        'require_total_like_count': requireTotalLikeCount,
        if (secretAnswer != null) 'secret_answer': secretAnswer,
        if (tags != null) 'tags': tags,
        if (replyGroup != null) 'reply_group': replyGroup,
        if (commentIgnoreGroup != null) 'comment_ignore_group': commentIgnoreGroup,
        if (dontAlertFollowers != null) 'dont_alert_followers': dontAlertFollowers,
        if (hideContacts != null) 'hide_contacts': hideContacts,
        if (allowAskHiddenContent != null) 'allow_ask_hidden_content': allowAskHiddenContent,
        if (scheduleDate != null) 'schedule_date': scheduleDate,
        if (scheduleTime != null) 'schedule_time': scheduleTime,
        if (watchThreadState != null) 'watch_thread_state': watchThreadState,
        if (watchThread != null) 'watch_thread': watchThread,
        if (watchThreadEmail != null) 'watch_thread_email': watchThreadEmail,
    };
    return post('/contests', body: bodyMap);
  }

  /// POST /claims — Create Claim
  ///
  /// Create a Claim. Required scopes: + **post**
  ///
  /// [asResponder] To whom the complaint is filed. Specify a nickname or a link to the profile.
  ///
  /// [asIsMarketDeal] Did you buy account on the market?
  ///
  /// [asMarketItemId] Market item id. Required if **as_is_market_deal** is 1.
  ///
  /// [asData] Contacts and wallets of the responder. Specify the known data about the responder, if any. Optional if **as_is_market_deal** is 0.
  ///
  /// [asAmount] Indicate the amount by which the responder deceived you.
  ///
  /// [currency] Currency of Claim.
  ///
  /// [transferType] The transaction took place through a guarantor or there was a transfer to the market with a hold? Required if **as_is_market_deal** is 0.
  ///
  /// [payClaim] Pay claim fee now or later. (Only for **transfer_type** = **notsafe**)
  ///
  /// [asFundsReceipt] Funds transfer receipt. Upload a receipt for the transfer of funds, use the "View receipt" button in your wallet. May be uploaded to [Imgur](https://imgur.com/upload). Write "no" if you have not paid.
  ///
  /// [asTgLoginScreenshot] Screenshot showing the respondent's Telegram login. If the correspondence was conducted in Telegram, upload a screenshot that will display the respondent's Telegram login against the background of your dialogue. The screenshot may be uploaded to [Imgur](https://imgur.com/upload). If the correspondence was conducted elsewhere, write "no".
  ///
  /// [tags] Thread tags.
  ///
  /// [hideContacts] Hide contacts.
  ///
  /// [allowAskHiddenContent] Allow ask hidden content.
  ///
  /// [replyGroup] Allow to reply only users with chosen or higher group.
  ///
  /// [commentIgnoreGroup] Allow commenting if user can't post in thread.
  ///
  /// [dontAlertFollowers] Don't alert followers about thread creation.
  ///
  /// [scheduleDate] Date to schedule thread creation (format: `DD-MM-YYYY`).
  ///
  /// [scheduleTime] Time to schedule thread creation (format: `HH:MM`).
  ///
  /// [watchThreadState] Watch thread state.
  ///
  /// [watchThread] Receive forum notifications of new posts in this thread.
  ///
  /// [watchThreadEmail] Receive email notifications of new posts in this thread.
  ///
  /// [postBody] You should describe what's happened. - describe the situation in a nutshell. If you wish, you can describe the situation in more detail using the "Spoiler" function.
  Future<Map<String, dynamic>> threadsClaim({
    required String asResponder,
    required bool asIsMarketDeal,
    required num asAmount,
    required String transferType,
    required String postBody,
    int? asMarketItemId,
    String? asData,
    String? currency,
    String? payClaim,
    String? asFundsReceipt,
    String? asTgLoginScreenshot,
    List<String>? tags,
    bool? hideContacts,
    bool? allowAskHiddenContent,
    int? replyGroup,
    bool? commentIgnoreGroup,
    bool? dontAlertFollowers,
    String? scheduleDate,
    String? scheduleTime,
    bool? watchThreadState,
    bool? watchThread,
    bool? watchThreadEmail,
  }) {
    final bodyMap = <String, dynamic>{
        'as_responder': asResponder,
        'as_is_market_deal': asIsMarketDeal,
        if (asMarketItemId != null) 'as_market_item_id': asMarketItemId,
        if (asData != null) 'as_data': asData,
        'as_amount': asAmount,
        if (currency != null) 'currency': currency,
        'transfer_type': transferType,
        if (payClaim != null) 'pay_claim': payClaim,
        if (asFundsReceipt != null) 'as_funds_receipt': asFundsReceipt,
        if (asTgLoginScreenshot != null) 'as_tg_login_screenshot': asTgLoginScreenshot,
        if (tags != null) 'tags': tags,
        if (hideContacts != null) 'hide_contacts': hideContacts,
        if (allowAskHiddenContent != null) 'allow_ask_hidden_content': allowAskHiddenContent,
        if (replyGroup != null) 'reply_group': replyGroup,
        if (commentIgnoreGroup != null) 'comment_ignore_group': commentIgnoreGroup,
        if (dontAlertFollowers != null) 'dont_alert_followers': dontAlertFollowers,
        if (scheduleDate != null) 'schedule_date': scheduleDate,
        if (scheduleTime != null) 'schedule_time': scheduleTime,
        if (watchThreadState != null) 'watch_thread_state': watchThreadState,
        if (watchThread != null) 'watch_thread': watchThread,
        if (watchThreadEmail != null) 'watch_thread_email': watchThreadEmail,
        'post_body': postBody,
    };
    return post('/claims', body: bodyMap);
  }

  /// GET /threads/{thread_id} — Get Thread
  ///
  /// Detail information of a thread. Required scopes: + **read**
  ///
  /// [threadId] Id of thread.
  ///
  /// [fieldsInclude] List of fields to include.
  Future<Map<String, dynamic>> threadsGet({
    required int threadId,
    List<String>? fieldsInclude,
  }) {
    final _queryArgs = <String, String>{
      if (fieldsInclude != null) 'fields_include': fieldsInclude!.join(','),
    };
    return get('/threads/$threadId', params: _queryArgs);
  }

  /// PUT /threads/{thread_id} — Edit thread
  ///
  /// Edit a thread. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  ///
  /// [title] Thread title.
  ///
  /// [titleEn] Thread title english.
  ///
  /// [prefixId] Prefix ids. Set "0" to remove all thread prefixes.
  ///
  /// [tags] Thread tags.
  ///
  /// [discussionOpen] Discussion state.
  ///
  /// [hideContacts] Hide contacts.
  ///
  /// [allowAskHiddenContent] Allow ask hidden content.
  ///
  /// [replyGroup] Allow to reply only users with chosen or higher group.
  ///
  /// [commentIgnoreGroup] Allow commenting if user can't post in thread.
  Future<Map<String, dynamic>> threadsEdit({
    required int threadId,
    String? title,
    String? titleEn,
    List<int>? prefixId,
    List<String>? tags,
    bool? discussionOpen,
    bool? hideContacts,
    bool? allowAskHiddenContent,
    int? replyGroup,
    bool? commentIgnoreGroup,
  }) {
    final bodyMap = <String, dynamic>{
        if (title != null) 'title': title,
        if (titleEn != null) 'title_en': titleEn,
        if (prefixId != null) 'prefix_id': prefixId,
        if (tags != null) 'tags': tags,
        if (discussionOpen != null) 'discussion_open': discussionOpen,
        if (hideContacts != null) 'hide_contacts': hideContacts,
        if (allowAskHiddenContent != null) 'allow_ask_hidden_content': allowAskHiddenContent,
        if (replyGroup != null) 'reply_group': replyGroup,
        if (commentIgnoreGroup != null) 'comment_ignore_group': commentIgnoreGroup,
    };
    return put('/threads/$threadId', body: bodyMap);
  }

  /// DELETE /threads/{thread_id} — Delete Thread
  ///
  /// Delete a thread. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsDelete({
    required int threadId,
  }) {
    return delete('/threads/$threadId');
  }

  /// POST /threads/{thread_id}/move — Move Thread
  ///
  /// Move a thread to another forum. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  ///
  /// [nodeId] Forum id.
  ///
  /// [title] Thread title.
  ///
  /// [titleEn] Thread title english.
  ///
  /// [prefixId] Prefix ids. Set "0" to remove all thread prefixes.
  ///
  /// [applyThreadPrefix] Apply thread prefix.
  ///
  /// [sendAlert] Send a notification to users who are followed to target node.
  Future<Map<String, dynamic>> threadsMove({
    required int threadId,
    required String nodeId,
    String? title,
    String? titleEn,
    List<int>? prefixId,
    bool? applyThreadPrefix,
    bool? sendAlert,
  }) {
    final bodyMap = <String, dynamic>{
        'node_id': nodeId,
        if (title != null) 'title': title,
        if (titleEn != null) 'title_en': titleEn,
        if (prefixId != null) 'prefix_id': prefixId,
        if (applyThreadPrefix != null) 'apply_thread_prefix': applyThreadPrefix,
        if (sendAlert != null) 'send_alert': sendAlert,
    };
    return post('/threads/$threadId/move', body: bodyMap);
  }

  /// POST /threads/{thread_id}/bump — Bump Thread
  ///
  /// Bump a thread. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsBump({
    required int threadId,
  }) {
    return post('/threads/$threadId/bump');
  }

  /// POST /threads/{thread_id}/hide — Hide Thread
  ///
  /// Hide a thread from your feed. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsHide({
    required int threadId,
  }) {
    return post('/threads/$threadId/hide');
  }

  /// POST /threads/{thread_id}/star — Bookmark Thread
  ///
  /// Bookmark a thread. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsStar({
    required int threadId,
  }) {
    return post('/threads/$threadId/star');
  }

  /// DELETE /threads/{thread_id}/star — Unbookmark Thread
  ///
  /// Unbookmark a thread. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsUnstar({
    required int threadId,
  }) {
    return delete('/threads/$threadId/star');
  }

  /// GET /threads/{thread_id}/followers — Get Thread Followers
  ///
  /// List of a thread's followers. For privacy reason, only the current user will be included
  /// in the list. Required scopes: + **read**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsFollowers({
    required int threadId,
  }) {
    return get('/threads/$threadId/followers');
  }

  /// POST /threads/{thread_id}/followers — Follow Thread
  ///
  /// Follow a thread. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  ///
  /// [email] Whether to receive notification as email.
  Future<Map<String, dynamic>> threadsFollow({
    required int threadId,
    bool? email,
  }) {
    final bodyMap = <String, dynamic>{
        if (email != null) 'email': email,
    };
    return post('/threads/$threadId/followers', body: bodyMap);
  }

  /// DELETE /threads/{thread_id}/followers — Unfollow Thread
  ///
  /// Unfollow a thread. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsUnfollow({
    required int threadId,
  }) {
    return delete('/threads/$threadId/followers');
  }

  /// GET /threads/followed — Get Followed Threads
  ///
  /// List of followed threads by current user. Required scopes: + **read**
  ///
  /// [total] If included in the request, only the thread count is returned as **threads_total**.
  ///
  /// [fieldsInclude] List of fields to include.
  Future<Map<String, dynamic>> threadsFollowed({
    bool? total,
    List<String>? fieldsInclude,
  }) {
    final _queryArgs = <String, String>{
      if (total != null) 'total': total!.toString(),
      if (fieldsInclude != null) 'fields_include': fieldsInclude!.join(','),
    };
    return get('/threads/followed', params: _queryArgs);
  }

  /// GET /threads/{thread_id}/navigation — Get Navigation Elements
  ///
  /// List of navigation elements to reach the specified thread. Required scopes: + **read**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsNavigation({
    required int threadId,
  }) {
    return get('/threads/$threadId/navigation');
  }

  /// GET /threads/{thread_id}/poll — Get Poll
  ///
  /// Detail information of a poll. Required scopes: + **read**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsPollGet({
    required int threadId,
  }) {
    return get('/threads/$threadId/poll');
  }

  /// POST /threads/{thread_id}/poll/votes — Vote Poll
  ///
  /// Vote on a thread poll. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  ///
  /// [responseId] The id of the response to vote for. Can be skipped if **response_ids** set.
  ///
  /// [responseIds] An array of ids of responses (if the poll allows multiple choices).
  Future<Map<String, dynamic>> threadsPollVote({
    required int threadId,
    int? responseId,
    List<int>? responseIds,
  }) {
    final bodyMap = <String, dynamic>{
        if (responseId != null) 'response_id': responseId,
        if (responseIds != null) 'response_ids': responseIds,
    };
    return post('/threads/$threadId/poll/votes', body: bodyMap);
  }

  /// GET /threads/new — Get Unread Threads
  ///
  /// List of unread threads (must be logged in). Required scopes: + **read**
  ///
  /// [limit] Maximum number of result threads. The limit may get decreased if the value is too large (depending on the system configuration).
  ///
  /// [forumId] Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
  ///
  /// [dataLimit] Number of thread data to be returned. Default value is 20.
  Future<Map<String, dynamic>> threadsUnread({
    int? limit,
    int? forumId,
    int? dataLimit,
  }) {
    final _queryArgs = <String, String>{
      if (limit != null) 'limit': limit!.toString(),
      if (forumId != null) 'forum_id': forumId!.toString(),
      if (dataLimit != null) 'data_limit': dataLimit!.toString(),
    };
    return get('/threads/new', params: _queryArgs);
  }

  /// GET /threads/recent — Get Recent Threads
  ///
  /// List of recent threads. Required scopes: + **read**
  ///
  /// [days] Maximum number of days to search for threads.
  ///
  /// [limit] Maximum number of result threads. The limit may get decreased if the value is too large.
  ///
  /// [forumId] Id of the container forum to search for threads. Child forums of the specified forum will be included in the search.
  ///
  /// [dataLimit] Number of thread data to be returned. Default value is 20.
  Future<Map<String, dynamic>> threadsRecent({
    int? days,
    int? limit,
    int? forumId,
    int? dataLimit,
  }) {
    final _queryArgs = <String, String>{
      if (days != null) 'days': days!.toString(),
      if (limit != null) 'limit': limit!.toString(),
      if (forumId != null) 'forum_id': forumId!.toString(),
      if (dataLimit != null) 'data_limit': dataLimit!.toString(),
    };
    return get('/threads/recent', params: _queryArgs);
  }

  /// POST /contests/{thread_id}/finish — Finish Contest
  ///
  /// Finishes a contest. Required scopes: + **post**
  ///
  /// [threadId] Id of thread.
  Future<Map<String, dynamic>> threadsFinish({
    required int threadId,
  }) {
    return post('/contests/$threadId/finish');
  }

  /// GET /posts — Get Posts
  ///
  /// List of posts in a thread (with pagination). Required scopes: + **read**
  ///
  /// [threadId] Id of the containing thread.
  ///
  /// [pageOfPostId] Id of a post, posts that are in the same page with the specified post will be returned. **thread_id** may be skipped.
  ///
  /// [page] Page number of posts.
  ///
  /// [limit] Number of posts in a page.
  ///
  /// [order] Ordering of posts.
  Future<Map<String, dynamic>> postsList({
    int? threadId,
    int? pageOfPostId,
    int? page,
    int? limit,
    String? order,
  }) {
    final _queryArgs = <String, String>{
      if (threadId != null) 'thread_id': threadId!.toString(),
      if (pageOfPostId != null) 'page_of_post_id': pageOfPostId!.toString(),
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
      if (order != null) 'order': order!,
    };
    return get('/posts', params: _queryArgs);
  }

  /// POST /posts — Create Post
  ///
  /// Create a new post. Required scopes: + **post**
  ///
  /// [postBody] Content of the new post.
  ///
  /// [threadId] Id of the target thread. **quote_post_id** can be skipped if this parameter is provided.
  ///
  /// [quotePostId] Id of the quote post. **thread_id** can be skipped if this parameter is provided.
  Future<Map<String, dynamic>> postsCreate({
    required String postBody,
    int? threadId,
    int? quotePostId,
  }) {
    final bodyMap = <String, dynamic>{
        'post_body': postBody,
        if (threadId != null) 'thread_id': threadId,
        if (quotePostId != null) 'quote_post_id': quotePostId,
    };
    return post('/posts', body: bodyMap);
  }

  /// GET /posts/{post_id} — Get Post
  ///
  /// Detail information of a post. Required scopes: + **read**
  ///
  /// [postId] Id of post.
  Future<Map<String, dynamic>> postsGet({
    required int postId,
  }) {
    return get('/posts/$postId');
  }

  /// PUT /posts/{post_id} — Edit Post
  ///
  /// Edit a post. Required scopes: + **post**
  ///
  /// [postId] Id of post.
  ///
  /// [postBody] Content of the post.
  Future<Map<String, dynamic>> postsEdit({
    required int postId,
    String? postBody,
  }) {
    final bodyMap = <String, dynamic>{
        if (postBody != null) 'post_body': postBody,
    };
    return put('/posts/$postId', body: bodyMap);
  }

  /// DELETE /posts/{post_id} — Delete Post
  ///
  /// Delete a post. Required scopes: + **post**
  ///
  /// [postId] Id of post.
  Future<Map<String, dynamic>> postsDelete({
    required int postId,
  }) {
    return delete('/posts/$postId');
  }

  /// GET /posts/{post_id}/likes — Get Post Likes
  ///
  /// List of users who liked a post. Required scopes: + **read**
  ///
  /// [postId] Id of post.
  ///
  /// [page] Page number of users.
  ///
  /// [limit] Number of users in a page.
  Future<Map<String, dynamic>> postsLikes({
    required int postId,
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/posts/$postId/likes', params: _queryArgs);
  }

  /// POST /posts/{post_id}/likes — Like Post
  ///
  /// Like a post. Required scopes: + **post**
  ///
  /// [postId] Id of post.
  Future<Map<String, dynamic>> postsLike({
    required int postId,
  }) {
    return post('/posts/$postId/likes');
  }

  /// DELETE /posts/{post_id}/likes — Unlike Post
  ///
  /// Unlike a post. Required scopes: + **post**
  ///
  /// [postId] Id of post.
  Future<Map<String, dynamic>> postsUnlike({
    required int postId,
  }) {
    return delete('/posts/$postId/likes');
  }

  /// GET /posts/{post_id}/report — Get Post Report Reasons
  ///
  /// Get post report reasons. Required scopes: + **read**
  ///
  /// [postId] Id of post.
  Future<Map<String, dynamic>> postsReportreasons({
    required int postId,
  }) {
    return get('/posts/$postId/report');
  }

  /// POST /posts/{post_id}/report — Report Post
  ///
  /// Report a post. Required scopes: + **post**
  ///
  /// [postId] Id of post.
  ///
  /// [message] Reason of the report.
  Future<Map<String, dynamic>> postsReport({
    required int postId,
    required String message,
  }) {
    final bodyMap = <String, dynamic>{
        'message': message,
    };
    return post('/posts/$postId/report', body: bodyMap);
  }

  /// GET /posts/comments — Get Post Comments
  ///
  /// List of post comments in a thread. Required scopes: + **read**
  ///
  /// [postId] Id of post.
  ///
  /// [before] The time in milliseconds (e.g. 1652177794083) before last comment date.
  ///
  /// [beforeComment] Comment id to get older comments.
  Future<Map<String, dynamic>> postsCommentsGet({
    required int postId,
    int? before,
    int? beforeComment,
  }) {
    final _queryArgs = <String, String>{
      'post_id': postId.toString(),
      if (before != null) 'before': before!.toString(),
      if (beforeComment != null) 'before_comment': beforeComment!.toString(),
    };
    return get('/posts/comments', params: _queryArgs);
  }

  /// POST /posts/comments — Create Post Comment
  ///
  /// Create a post comment. Required scopes: + **post**
  ///
  /// [postId] Id of post.
  ///
  /// [commentBody] Content of the a post comment.
  Future<Map<String, dynamic>> postsCommentsCreate({
    required int postId,
    required String commentBody,
  }) {
    final bodyMap = <String, dynamic>{
        'post_id': postId,
        'comment_body': commentBody,
    };
    return post('/posts/comments', body: bodyMap);
  }

  /// PUT /posts/comments — Edit Post Comment
  ///
  /// Edit a post comment. Required scopes: + **post**
  ///
  /// [postCommentId] Id of post.
  ///
  /// [commentBody] Content of the new post comment.
  Future<Map<String, dynamic>> postsCommentsEdit({
    required int postCommentId,
    required String commentBody,
  }) {
    final bodyMap = <String, dynamic>{
        'post_comment_id': postCommentId,
        'comment_body': commentBody,
    };
    return put('/posts/comments', body: bodyMap);
  }

  /// DELETE /posts/comments — Delete Post Comment
  ///
  /// Delete a post comment. Required scopes: + **post**
  Future<Map<String, dynamic>> postsCommentsDelete() {
    return delete('/posts/comments');
  }

  /// POST /posts/comments/report — Report Post Comment
  ///
  /// Report a post comment. Required scopes: + **post**
  ///
  /// [postCommentId] Id of post comment.
  ///
  /// [message] Reason of the report.
  Future<Map<String, dynamic>> postsCommentsReport({
    required int postCommentId,
    required String message,
  }) {
    final bodyMap = <String, dynamic>{
        'post_comment_id': postCommentId,
        'message': message,
    };
    return post('/posts/comments/report', body: bodyMap);
  }

  /// GET /users — Get Users
  ///
  /// List of users (with pagination). Required scopes: + **read**
  ///
  /// [page] Page number of users.
  ///
  /// [limit] Number of users in a page.
  ///
  /// [fieldsInclude] List of fields to include.
  Future<Map<String, dynamic>> usersList({
    int? page,
    int? limit,
    List<String>? fieldsInclude,
  }) {
    final _queryArgs = <String, String>{
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
      if (fieldsInclude != null) 'fields_include': fieldsInclude!.join(','),
    };
    return get('/users', params: _queryArgs);
  }

  /// GET /users/fields — Get User Fields
  ///
  /// List of user fields. Required scopes: + **read**
  Future<Map<String, dynamic>> usersFields() {
    return get('/users/fields');
  }

  /// GET /users/find — Find Users
  ///
  /// List of users filtered by username, email or custom fields. Required scopes: + **read**
  ///
  /// [username] Username to filter. Usernames start with the query will be returned.
  ///
  /// [customFields] Custom fields to filter. Example: **custom_fields[telegram]=telegramLogin**.
  ///
  /// [fieldsInclude] List of fields to include.
  Future<Map<String, dynamic>> usersFind({
    String? username,
    Map<String, dynamic>? customFields,
    List<String>? fieldsInclude,
  }) {
    final _queryArgs = <String, String>{
      if (username != null) 'username': username!,
      if (customFields != null) 'custom_fields': customFields!.toString(),
      if (fieldsInclude != null) 'fields_include': fieldsInclude!.join(','),
    };
    return get('/users/find', params: _queryArgs);
  }

  /// GET /users/{user_id} — Get User
  ///
  /// Detail information of a user. Required scopes: + **read** + **basic**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [fieldsInclude] List of fields to include.
  Future<Map<String, dynamic>> usersGet({
    required String userId,
    List<String>? fieldsInclude,
  }) {
    final _queryArgs = <String, String>{
      if (fieldsInclude != null) 'fields_include': fieldsInclude!.join(','),
    };
    return get('/users/$userId', params: _queryArgs);
  }

  /// PUT /users/{user_id} — Edit User
  ///
  /// Edit a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [username] New username.
  ///
  /// [userTitle] New custom title of the user.
  ///
  /// [displayGroupId] Id of the group you want to display.
  ///
  /// [displayIconGroupId] Id of the icon group you want to display.
  ///
  /// [displayBannerId] Id of the banner you want to display.
  ///
  /// [convWelcomeMessage] This message is shown when someone wants to write to you.
  ///
  /// [userDobDay] Your date of birth (day).
  ///
  /// [userDobMonth] Your date of birth (month).
  ///
  /// [userDobYear] Your date of birth (year).
  ///
  /// [secretAnswer] Secret answer.
  ///
  /// [secretAnswerType] Secret answer type.
  ///
  /// [shortLink] Profile short link.
  ///
  /// [languageId] User interface language ID.
  ///
  /// [gender] User gender.
  ///
  /// [timezone] User timezone.
  ///
  /// [receiveAdminEmail] Whether to receive admin emails.
  ///
  /// [activityVisible] Whether user activity is visible.
  ///
  /// [showDobDate] Show date of birth (day and month).
  ///
  /// [showDobYear] Show year of birth.
  ///
  /// [hideUsernameChangeLogs] Hide username change logs.
  ///
  /// [allowViewProfile] Who can view your profile.
  ///
  /// [allowPostProfile] Who can post on your profile.
  ///
  /// [allowSendPersonalConversation] Who can send you personal conversations.
  ///
  /// [allowInviteGroup] Who can invite you to groups.
  ///
  /// [allowReceiveNewsFeed] Who can see your news feed.
  ///
  /// [alert] Alert settings.
  ///
  /// [fields] Custom user profile fields.
  Future<Map<String, dynamic>> usersEdit({
    required String userId,
    String? username,
    String? userTitle,
    int? displayGroupId,
    int? displayIconGroupId,
    int? displayBannerId,
    String? convWelcomeMessage,
    int? userDobDay,
    int? userDobMonth,
    int? userDobYear,
    String? secretAnswer,
    int? secretAnswerType,
    String? shortLink,
    int? languageId,
    String? gender,
    String? timezone,
    bool? receiveAdminEmail,
    bool? activityVisible,
    bool? showDobDate,
    bool? showDobYear,
    bool? hideUsernameChangeLogs,
    String? allowViewProfile,
    String? allowPostProfile,
    String? allowSendPersonalConversation,
    String? allowInviteGroup,
    String? allowReceiveNewsFeed,
    Map<String, dynamic>? alert,
    Map<String, dynamic>? fields,
  }) {
    final bodyMap = <String, dynamic>{
        if (username != null) 'username': username,
        if (userTitle != null) 'user_title': userTitle,
        if (displayGroupId != null) 'display_group_id': displayGroupId,
        if (displayIconGroupId != null) 'display_icon_group_id': displayIconGroupId,
        if (displayBannerId != null) 'display_banner_id': displayBannerId,
        if (convWelcomeMessage != null) 'conv_welcome_message': convWelcomeMessage,
        if (userDobDay != null) 'user_dob_day': userDobDay,
        if (userDobMonth != null) 'user_dob_month': userDobMonth,
        if (userDobYear != null) 'user_dob_year': userDobYear,
        if (secretAnswer != null) 'secret_answer': secretAnswer,
        if (secretAnswerType != null) 'secret_answer_type': secretAnswerType,
        if (shortLink != null) 'short_link': shortLink,
        if (languageId != null) 'language_id': languageId,
        if (gender != null) 'gender': gender,
        if (timezone != null) 'timezone': timezone,
        if (receiveAdminEmail != null) 'receive_admin_email': receiveAdminEmail,
        if (activityVisible != null) 'activity_visible': activityVisible,
        if (showDobDate != null) 'show_dob_date': showDobDate,
        if (showDobYear != null) 'show_dob_year': showDobYear,
        if (hideUsernameChangeLogs != null) 'hide_username_change_logs': hideUsernameChangeLogs,
        if (allowViewProfile != null) 'allow_view_profile': allowViewProfile,
        if (allowPostProfile != null) 'allow_post_profile': allowPostProfile,
        if (allowSendPersonalConversation != null) 'allow_send_personal_conversation': allowSendPersonalConversation,
        if (allowInviteGroup != null) 'allow_invite_group': allowInviteGroup,
        if (allowReceiveNewsFeed != null) 'allow_receive_news_feed': allowReceiveNewsFeed,
        if (alert != null) 'alert': alert,
        if (fields != null) 'fields': fields,
    };
    return put('/users/$userId', body: bodyMap);
  }

  /// GET /users/{user_id}/claims — Get User Claims
  ///
  /// Get user claims. Required scopes: + **read**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [type] Filter claims by their type.
  ///
  /// [claimState] Filter claims by their state.
  Future<Map<String, dynamic>> usersClaims({
    required String userId,
    String? type,
    String? claimState,
  }) {
    final _queryArgs = <String, String>{
      if (type != null) 'type': type!,
      if (claimState != null) 'claim_state': claimState!,
    };
    return get('/users/$userId/claims', params: _queryArgs);
  }

  /// POST /users/{user_id}/avatar — Upload Avatar
  ///
  /// Upload avatar for a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [avatar] Binary data of the avatar.
  ///
  /// [x] The starting point of the selection by width. Default value - 0
  ///
  /// [y] The starting point of the selection by height. Default value - 0
  ///
  /// [crop] Selection size.
  Future<Map<String, dynamic>> usersAvatarUpload({
    required String userId,
    required String avatar,
    int? x,
    int? y,
    int? crop,
  }) {
    final bodyMap = <String, dynamic>{
        'avatar': avatar,
        if (x != null) 'x': x,
        if (y != null) 'y': y,
        if (crop != null) 'crop': crop,
    };
    return post('/users/$userId/avatar', body: bodyMap);
  }

  /// DELETE /users/{user_id}/avatar — Delete Avatar
  ///
  /// Delete avatar for a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  Future<Map<String, dynamic>> usersAvatarDelete({
    required String userId,
  }) {
    return delete('/users/$userId/avatar');
  }

  /// POST /users/{user_id}/avatar/crop — Crop Avatar
  ///
  /// Crop avatar for a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [x] The starting point of the selection by width. Default value - 0
  ///
  /// [y] The starting point of the selection by height. Default value - 0
  ///
  /// [crop] Selection size.
  Future<Map<String, dynamic>> usersAvatarCrop({
    required String userId,
    int? x,
    int? y,
    int? crop,
  }) {
    final bodyMap = <String, dynamic>{
        if (x != null) 'x': x,
        if (y != null) 'y': y,
        if (crop != null) 'crop': crop,
    };
    return post('/users/$userId/avatar/crop', body: bodyMap);
  }

  /// POST /users/{user_id}/background — Upload Background
  ///
  /// Upload background for a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [background] Binary data of the background. Background image must be 1920x1080 pixels
  ///
  /// [x] The starting point of the selection by width. Default value - 0
  ///
  /// [y] The starting point of the selection by height. Default value - 0
  ///
  /// [crop] Selection size.
  Future<Map<String, dynamic>> usersBackgroundUpload({
    required String userId,
    required String background,
    int? x,
    int? y,
    int? crop,
  }) {
    final bodyMap = <String, dynamic>{
        'background': background,
        if (x != null) 'x': x,
        if (y != null) 'y': y,
        if (crop != null) 'crop': crop,
    };
    return post('/users/$userId/background', body: bodyMap);
  }

  /// DELETE /users/{user_id}/background — Delete Background
  ///
  /// Delete background for a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  Future<Map<String, dynamic>> usersBackgroundDelete({
    required String userId,
  }) {
    return delete('/users/$userId/background');
  }

  /// POST /users/{user_id}/background/crop — Crop Background
  ///
  /// Crop background for a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [x] The starting point of the selection by width. Default value - 0
  ///
  /// [y] The starting point of the selection by height. Default value - 0
  ///
  /// [crop] Selection size.
  Future<Map<String, dynamic>> usersBackgroundCrop({
    required String userId,
    int? x,
    int? y,
    int? crop,
  }) {
    final bodyMap = <String, dynamic>{
        if (x != null) 'x': x,
        if (y != null) 'y': y,
        if (crop != null) 'crop': crop,
    };
    return post('/users/$userId/background/crop', body: bodyMap);
  }

  /// GET /users/{user_id}/followers — Get User Followers
  ///
  /// List of a user's followers. Required scopes: + **read**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [order] Ordering of followers.
  ///
  /// [page] Page number of followers.
  ///
  /// [limit] Number of followers in a page.
  Future<Map<String, dynamic>> usersFollowers({
    required String userId,
    String? order,
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (order != null) 'order': order!,
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/users/$userId/followers', params: _queryArgs);
  }

  /// POST /users/{user_id}/followers — Follow User
  ///
  /// Follow a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  Future<Map<String, dynamic>> usersFollow({
    required String userId,
  }) {
    return post('/users/$userId/followers');
  }

  /// DELETE /users/{user_id}/followers — Unfollow User
  ///
  /// Unfollow a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  Future<Map<String, dynamic>> usersUnfollow({
    required String userId,
  }) {
    return delete('/users/$userId/followers');
  }

  /// GET /users/{user_id}/followings — Get Followed Users By User
  ///
  /// List of users whom are followed by a user. Required scopes: + **read**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [order] Ordering of users.
  ///
  /// [page] Page number of users.
  ///
  /// [limit] Number of users in a page.
  Future<Map<String, dynamic>> usersFollowings({
    required String userId,
    String? order,
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (order != null) 'order': order!,
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/users/$userId/followings', params: _queryArgs);
  }

  /// GET /users/{user_id}/likes — Get User Likes
  ///
  /// Get information about user likes. Required scopes: + **read**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [nodeId] Filter by forum section.
  ///
  /// [likeType] Like type.
  ///
  /// [type] Likes type.
  ///
  /// [page] Page number.
  ///
  /// [contentType] Content type.
  ///
  /// [searchUserId] Get only likes from specified user.
  ///
  /// [stats] Show weekly statistics.
  Future<Map<String, dynamic>> usersLikes({
    required String userId,
    int? nodeId,
    String? likeType,
    String? type,
    int? page,
    String? contentType,
    int? searchUserId,
    bool? stats,
  }) {
    final _queryArgs = <String, String>{
      if (nodeId != null) 'node_id': nodeId!.toString(),
      if (likeType != null) 'like_type': likeType!,
      if (type != null) 'type': type!,
      if (page != null) 'page': page!.toString(),
      if (contentType != null) 'content_type': contentType!,
      if (searchUserId != null) 'search_user_id': searchUserId!.toString(),
      if (stats != null) 'stats': stats!.toString(),
    };
    return get('/users/$userId/likes', params: _queryArgs);
  }

  /// GET /users/ignored — Get Ignored Users
  ///
  /// List of ignored users of current user. Required scopes: + **read**
  ///
  /// [total] If included in the request, only the user count is returned as **users_total**.
  Future<Map<String, dynamic>> usersIgnored({
    bool? total,
  }) {
    final _queryArgs = <String, String>{
      if (total != null) 'total': total!.toString(),
    };
    return get('/users/ignored', params: _queryArgs);
  }

  /// POST /users/{user_id}/ignore — Ignore User
  ///
  /// Ignore a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  Future<Map<String, dynamic>> usersIgnore({
    required String userId,
  }) {
    return post('/users/$userId/ignore');
  }

  /// PUT /users/{user_id}/ignore — Edit Ignoring Options
  ///
  /// Edit ignoring options. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [ignoreConversations] Ignore user's conversations.
  ///
  /// [ignoreContent] Ignore user's content.
  ///
  /// [restrictViewProfile] Restrict user from viewing your profile.
  Future<Map<String, dynamic>> usersIgnoreedit({
    required String userId,
    bool? ignoreConversations,
    bool? ignoreContent,
    bool? restrictViewProfile,
  }) {
    final _queryArgs = <String, String>{
      if (ignoreConversations != null) 'ignore_conversations': ignoreConversations!.toString(),
      if (ignoreContent != null) 'ignore_content': ignoreContent!.toString(),
      if (restrictViewProfile != null) 'restrict_view_profile': restrictViewProfile!.toString(),
    };
    return put('/users/$userId/ignore', params: _queryArgs);
  }

  /// DELETE /users/{user_id}/ignore — Unignore User
  ///
  /// Stop ignoring a user. Required scopes: + **post**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  Future<Map<String, dynamic>> usersUnignore({
    required String userId,
  }) {
    return delete('/users/$userId/ignore');
  }

  /// GET /users/{user_id}/timeline — Get Contents
  ///
  /// List of contents created by user (with pagination). Required scopes: + **read**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [page] Page number of contents.
  ///
  /// [limit] Number of contents in a page.
  Future<Map<String, dynamic>> usersContents({
    required String userId,
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/users/$userId/timeline', params: _queryArgs);
  }

  /// GET /users/{user_id}/trophies — Get Trophies
  ///
  /// List of user trophies. Required scopes: + **read**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  Future<Map<String, dynamic>> usersTrophies({
    required String userId,
  }) {
    return get('/users/$userId/trophies');
  }

  /// GET /users/secret-answer/types — Get Secret Answer Types
  ///
  /// Get available secret answer types for user account security. Required scopes: + **read**
  Future<Map<String, dynamic>> usersSecretanswertypes() {
    return get('/users/secret-answer/types');
  }

  /// POST /account/secret-answer/reset — Reset Secret Answer
  ///
  /// Request a reset of the secret answer for the account. Required scopes: + **post**
  Future<Map<String, dynamic>> usersSaReset() {
    return post('/account/secret-answer/reset');
  }

  /// DELETE /account/secret-answer/reset — Cancel Secret Answer Reset
  ///
  /// Cancel a pending secret answer reset request for the account. Required scopes: +
  /// **post**
  Future<Map<String, dynamic>> usersSaCancelreset() {
    return delete('/account/secret-answer/reset');
  }

  /// GET /users/{user_id}/profile-posts — Get Profile Posts
  ///
  /// List of profile posts (with pagination). Required scopes: + **read**
  ///
  /// [userId] User ID. > You can use shortlink `me` to interact with your profile.
  ///
  /// [postsUserId] Filter to get only posts from the specified user.
  ///
  /// [page] Page number of contents.
  ///
  /// [limit] Number of contents in a page.
  ///
  /// [fieldsInclude] List of fields to include.
  Future<Map<String, dynamic>> profilepostsList({
    required String userId,
    int? postsUserId,
    int? page,
    int? limit,
    List<String>? fieldsInclude,
  }) {
    final _queryArgs = <String, String>{
      if (postsUserId != null) 'posts_user_id': postsUserId!.toString(),
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
      if (fieldsInclude != null) 'fields_include': fieldsInclude!.join(','),
    };
    return get('/users/$userId/profile-posts', params: _queryArgs);
  }

  /// GET /profile-posts/{profile_post_id} — Get Profile Post
  ///
  /// Detail information of a profile post. Required scopes: + **read**
  ///
  /// [profilePostId] Id of profile post.
  Future<Map<String, dynamic>> profilepostsGet({
    required int profilePostId,
  }) {
    return get('/profile-posts/$profilePostId');
  }

  /// PUT /profile-posts/{profile_post_id} — Edit Profile Post
  ///
  /// Edit a profile post. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  ///
  /// [postBody] New content of the profile post.
  ///
  /// [disableComments] Disable comments.
  Future<Map<String, dynamic>> profilepostsEdit({
    required int profilePostId,
    String? postBody,
    bool? disableComments,
  }) {
    final bodyMap = <String, dynamic>{
        if (postBody != null) 'post_body': postBody,
        if (disableComments != null) 'disable_comments': disableComments,
    };
    return put('/profile-posts/$profilePostId', body: bodyMap);
  }

  /// DELETE /profile-posts/{profile_post_id} — Delete Profile Post
  ///
  /// Delete a profile post. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  ///
  /// [reason] Reason of the profile post removal.
  Future<Map<String, dynamic>> profilepostsDelete({
    required int profilePostId,
    String? reason,
  }) {
    final _queryArgs = <String, String>{
      if (reason != null) 'reason': reason!,
    };
    return delete('/profile-posts/$profilePostId', params: _queryArgs);
  }

  /// GET /profile-posts/{profile_post_id}/report — Get Profile Post Report Reasons
  ///
  /// Get Profile Post Report Reasons. Required scopes: + **read**
  ///
  /// [profilePostId] Id of profile post.
  Future<Map<String, dynamic>> profilepostsReportreasons({
    required int profilePostId,
  }) {
    return get('/profile-posts/$profilePostId/report');
  }

  /// POST /profile-posts/{profile_post_id}/report — Report a Profile Post
  ///
  /// Report a profile post. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  ///
  /// [message] Reason of the report.
  Future<Map<String, dynamic>> profilepostsReport({
    required int profilePostId,
    required String message,
  }) {
    final bodyMap = <String, dynamic>{
        'message': message,
    };
    return post('/profile-posts/$profilePostId/report', body: bodyMap);
  }

  /// POST /profile-posts — Create Profile Post
  ///
  /// Create a profile post on a user profile. Required scopes: + **post**
  ///
  /// [postBody] Content of a profile post.
  Future<Map<String, dynamic>> profilepostsCreate({
    required String userId,
    required String postBody,
  }) {
    final bodyMap = <String, dynamic>{
        'user_id': userId,
        'post_body': postBody,
    };
    return post('/profile-posts', body: bodyMap);
  }

  /// POST /profile-posts/{profile_post_id}/stick — Stick Profile Post
  ///
  /// Stick a profile post. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  Future<Map<String, dynamic>> profilepostsStick({
    required int profilePostId,
  }) {
    return post('/profile-posts/$profilePostId/stick');
  }

  /// DELETE /profile-posts/{profile_post_id}/stick — Unstick Profile Post
  ///
  /// Unstick a profile post. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  Future<Map<String, dynamic>> profilepostsUnstick({
    required int profilePostId,
  }) {
    return delete('/profile-posts/$profilePostId/stick');
  }

  /// GET /profile-posts/{profile_post_id}/likes — Get Profile Post Likes
  ///
  /// List of users who liked a profile post. Required scopes: + **read**
  ///
  /// [profilePostId] Id of profile post.
  Future<Map<String, dynamic>> profilepostsLikes({
    required int profilePostId,
  }) {
    return get('/profile-posts/$profilePostId/likes');
  }

  /// POST /profile-posts/{profile_post_id}/likes — Like Profile Post
  ///
  /// Like a profile post. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  Future<Map<String, dynamic>> profilepostsLike({
    required int profilePostId,
  }) {
    return post('/profile-posts/$profilePostId/likes');
  }

  /// DELETE /profile-posts/{profile_post_id}/likes — Unlike Profile Post
  ///
  /// Unlike a profile post. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  Future<Map<String, dynamic>> profilepostsUnlike({
    required int profilePostId,
  }) {
    return delete('/profile-posts/$profilePostId/likes');
  }

  /// GET /profile-posts/comments — Get Profile Post Comments
  ///
  /// List of comments of a profile post. Required scopes: + **read**
  ///
  /// [profilePostId] Id of profile post.
  ///
  /// [before] Date to get older comments. Please note that this entry point does not support the page parameter but it still does support **limit**.
  ///
  /// [limit] Number of profile posts in a page.
  Future<Map<String, dynamic>> profilepostsCommentsList({
    required int profilePostId,
    int? before,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      'profile_post_id': profilePostId.toString(),
      if (before != null) 'before': before!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/profile-posts/comments', params: _queryArgs);
  }

  /// POST /profile-posts/comments — Create Profile Post Comment
  ///
  /// Create a new profile post comment. Required scopes: + **post**
  ///
  /// [profilePostId] Id of profile post.
  ///
  /// [commentBody] Content of the new profile post comment.
  Future<Map<String, dynamic>> profilepostsCommentsCreate({
    required int profilePostId,
    required String commentBody,
  }) {
    final bodyMap = <String, dynamic>{
        'profile_post_id': profilePostId,
        'comment_body': commentBody,
    };
    return post('/profile-posts/comments', body: bodyMap);
  }

  /// PUT /profile-posts/comments — Edit Profile Post Comment
  ///
  /// Edit a profile post comment. Required scopes: + **post**
  ///
  /// [commentId] Id of profile post comment.
  ///
  /// [commentBody] New content for the profile post comment.
  Future<Map<String, dynamic>> profilepostsCommentsEdit({
    required int commentId,
    required String commentBody,
  }) {
    final bodyMap = <String, dynamic>{
        'comment_id': commentId,
        'comment_body': commentBody,
    };
    return put('/profile-posts/comments', body: bodyMap);
  }

  /// DELETE /profile-posts/comments — Delete Profile Post Comment
  ///
  /// Delete a profile post comment. Required scopes: + **post**
  Future<Map<String, dynamic>> profilepostsCommentsDelete() {
    return delete('/profile-posts/comments');
  }

  /// GET /profile-posts/{profile_post_id}/comments/{comment_id} — Get Profile Post Comment
  ///
  /// Detail information of a profile post comment. Required scopes: + **read**
  ///
  /// [profilePostId] Id of profile post.
  ///
  /// [commentId] Id of profile post comment.
  Future<Map<String, dynamic>> profilepostsCommentsGet({
    required int profilePostId,
    required int commentId,
  }) {
    return get('/profile-posts/$profilePostId/comments/$commentId');
  }

  /// POST /profile-posts/comments/{comment_id}/report — Report a Profile Post Comment
  ///
  /// Report a profile post comment. Required scopes: + **post**
  ///
  /// [commentId] Id of profile post comment.
  ///
  /// [message] Reason of the report.
  Future<Map<String, dynamic>> profilepostsCommentsReport({
    required int commentId,
    required String message,
  }) {
    final bodyMap = <String, dynamic>{
        'message': message,
    };
    return post('/profile-posts/comments/$commentId/report', body: bodyMap);
  }

  /// GET /conversations — Get Conversations
  ///
  /// List of conversations (with pagination). Required scopes: + **read** + **conversate**
  ///
  /// [folder] Filter conversations by folder.
  ///
  /// [page] Page number of conversations.
  ///
  /// [limit] Number of conversations in a page.
  Future<Map<String, dynamic>> conversationsList({
    String? folder,
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (folder != null) 'folder': folder!,
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/conversations', params: _queryArgs);
  }

  /// POST /conversations — Create Conversation
  ///
  /// Create a new conversation. Required scopes: + **post** + **conversate**
  ///
  /// [recipientId] Id of recipient. Required if **is_group=false**.
  ///
  /// [recipients] List of recipients username's. Max recipients count is 10. Required if **is_group=true**.
  ///
  /// [isGroup] Is group. Set **false** if personal conversation, or set **true** if group.
  ///
  /// [title] The title of new conversation. Required if **is_group=1**.
  ///
  /// [openInvite] Open invite.
  ///
  /// [allowEditMessages] Allow edit messages.
  ///
  /// [allowStickyMessages] Allow members to stick messages.
  ///
  /// [allowDeleteOwnMessages] Allow members to delete their own messages.
  ///
  /// [messageBody] First message. Required if **is_group**=false
  Future<Map<String, dynamic>> conversationsCreate({
    int? recipientId,
    List<String>? recipients,
    bool? isGroup,
    String? title,
    bool? openInvite,
    bool? allowEditMessages,
    bool? allowStickyMessages,
    bool? allowDeleteOwnMessages,
    String? messageBody,
  }) {
    final bodyMap = <String, dynamic>{
        if (recipientId != null) 'recipient_id': recipientId,
        if (recipients != null) 'recipients': recipients,
        if (isGroup != null) 'is_group': isGroup,
        if (title != null) 'title': title,
        if (openInvite != null) 'open_invite': openInvite,
        if (allowEditMessages != null) 'allow_edit_messages': allowEditMessages,
        if (allowStickyMessages != null) 'allow_sticky_messages': allowStickyMessages,
        if (allowDeleteOwnMessages != null) 'allow_delete_own_messages': allowDeleteOwnMessages,
        if (messageBody != null) 'message_body': messageBody,
    };
    return post('/conversations', body: bodyMap);
  }

  /// PUT /conversations — Edit Conversation
  ///
  /// Edit conversation. Required scopes: + **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [title] New conversation title.
  ///
  /// [openInvite] Allow members to invite others.
  ///
  /// [historyOpen] Make conversation history visible to new members.
  ///
  /// [allowEditMessages] Allow members to edit their own messages.
  ///
  /// [allowStickyMessages] Allow members to stick messages.
  ///
  /// [allowDeleteOwnMessages] Allow members to delete their own messages.
  Future<Map<String, dynamic>> conversationsUpdate({
    required int conversationId,
    String? title,
    bool? openInvite,
    bool? historyOpen,
    bool? allowEditMessages,
    bool? allowStickyMessages,
    bool? allowDeleteOwnMessages,
  }) {
    final bodyMap = <String, dynamic>{
        'conversation_id': conversationId,
        if (title != null) 'title': title,
        if (openInvite != null) 'open_invite': openInvite,
        if (historyOpen != null) 'history_open': historyOpen,
        if (allowEditMessages != null) 'allow_edit_messages': allowEditMessages,
        if (allowStickyMessages != null) 'allow_sticky_messages': allowStickyMessages,
        if (allowDeleteOwnMessages != null) 'allow_delete_own_messages': allowDeleteOwnMessages,
    };
    return put('/conversations', body: bodyMap);
  }

  /// DELETE /conversations — Leave Conversation
  ///
  /// Leave the conversation. Required scopes: + **post** + **conversate**
  Future<Map<String, dynamic>> conversationsDelete() {
    return delete('/conversations');
  }

  /// POST /conversations/start — Start Conversation
  ///
  /// Start a new conversation with a user. Required scopes: + **conversate**
  Future<Map<String, dynamic>> conversationsStart({
    required String userId,
  }) {
    final bodyMap = <String, dynamic>{
        'user_id': userId,
    };
    return post('/conversations/start', body: bodyMap);
  }

  /// POST /conversations/save — Send Content To Saved Messages
  ///
  /// Send content to Saved Messages. Required scopes: + **conversate**
  ///
  /// [link] Content url.
  Future<Map<String, dynamic>> conversationsSave({
    required String link,
  }) {
    final bodyMap = <String, dynamic>{
        'link': link,
    };
    return post('/conversations/save', body: bodyMap);
  }

  /// GET /conversations/{conversation_id} — Get Conversation
  ///
  /// Detail information of a conversation. Required scopes: + **read** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  Future<Map<String, dynamic>> conversationsGet({
    required int conversationId,
  }) {
    return get('/conversations/$conversationId');
  }

  /// GET /conversations/{conversation_id}/messages — Get Conversation Messages
  ///
  /// List of messages in a conversation (with pagination). Required scopes: + **read** +
  /// **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [page] Page number of messages.
  ///
  /// [limit] Number of messages in a page.
  ///
  /// [order] Ordering of messages.
  ///
  /// [before] Date to get older messages.
  ///
  /// [after] Date to get newer messages.
  Future<Map<String, dynamic>> conversationsMessagesList({
    required int conversationId,
    int? page,
    int? limit,
    String? order,
    int? before,
    int? after,
  }) {
    final _queryArgs = <String, String>{
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
      if (order != null) 'order': order!,
      if (before != null) 'before': before!.toString(),
      if (after != null) 'after': after!.toString(),
    };
    return get('/conversations/$conversationId/messages', params: _queryArgs);
  }

  /// POST /conversations/{conversation_id}/messages — Create Conversation Message
  ///
  /// Create a new conversation message. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [replyMessageId] ID of the message being replied to.
  ///
  /// [messageBody] Content of the new message.
  Future<Map<String, dynamic>> conversationsMessagesCreate({
    required int conversationId,
    required String messageBody,
    int? replyMessageId,
  }) {
    final bodyMap = <String, dynamic>{
        if (replyMessageId != null) 'reply_message_id': replyMessageId,
        'message_body': messageBody,
    };
    return post('/conversations/$conversationId/messages', body: bodyMap);
  }

  /// POST /conversations/search — Search Conversations Messages
  ///
  /// Search for conversations messages or recipients. Required scopes: + **read** +
  /// **conversate**
  ///
  /// [q] Search query string.
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [searchRecipients] Search for recipients.
  Future<Map<String, dynamic>> conversationsSearch({
    String? q,
    int? conversationId,
    bool? searchRecipients,
  }) {
    final bodyMap = <String, dynamic>{
        if (q != null) 'q': q,
        if (conversationId != null) 'conversation_id': conversationId,
        if (searchRecipients != null) 'search_recipients': searchRecipients,
    };
    return post('/conversations/search', body: bodyMap);
  }

  /// GET /conversations/messages/{message_id} — Get Conversation Message
  ///
  /// Detail information of a message. Required scopes: + **read** + **conversate**
  ///
  /// [messageId] Id of message.
  Future<Map<String, dynamic>> conversationsMessagesGet({
    required int messageId,
  }) {
    return get('/conversations/messages/$messageId');
  }

  /// PUT /conversations/{conversation_id}/messages/{message_id} — Edit Conversation Message
  ///
  /// Edit a message. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [messageId] Id of message.
  ///
  /// [messageBody] New content of the message.
  Future<Map<String, dynamic>> conversationsMessagesEdit({
    required int conversationId,
    required int messageId,
    required String messageBody,
  }) {
    final bodyMap = <String, dynamic>{
        'message_body': messageBody,
    };
    return put('/conversations/$conversationId/messages/$messageId', body: bodyMap);
  }

  /// DELETE /conversations/{conversation_id}/messages/{message_id} — Delete Conversation Message
  ///
  /// Deletes a message from a conversation. Required scopes: + **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [messageId] Id of message.
  Future<Map<String, dynamic>> conversationsMessagesDelete({
    required int conversationId,
    required int messageId,
  }) {
    return delete('/conversations/$conversationId/messages/$messageId');
  }

  /// POST /conversations/{conversation_id}/invite — Invite Users to Conversation
  ///
  /// Invite one or more users to an existing conversation. Required scopes: + **conversate**
  /// + **post**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [recipients] List of recipients username's.
  Future<Map<String, dynamic>> conversationsInvite({
    required int conversationId,
    required List<String> recipients,
  }) {
    final bodyMap = <String, dynamic>{
        'recipients': recipients,
    };
    return post('/conversations/$conversationId/invite', body: bodyMap);
  }

  /// POST /conversations/{conversation_id}/kick — Kick User from Conversation
  ///
  /// Kicks a user from a conversation. Required scopes: + **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [userId] Id of user to kick from conversation.
  Future<Map<String, dynamic>> conversationsKick({
    required int conversationId,
    required int userId,
  }) {
    final bodyMap = <String, dynamic>{
        'user_id': userId,
    };
    return post('/conversations/$conversationId/kick', body: bodyMap);
  }

  /// POST /conversations/{conversation_id}/read — Read a Conversation
  ///
  /// Read a specific conversation. Required scopes: + **conversate**
  ///
  /// [conversationId] Id of conversation.
  Future<Map<String, dynamic>> conversationsRead({
    required int conversationId,
  }) {
    return post('/conversations/$conversationId/read');
  }

  /// POST /conversations/read-all — Read All Conversations
  ///
  /// Mark all conversations as read. Required scopes: + **read** + **conversate**
  Future<Map<String, dynamic>> conversationsReadall() {
    return post('/conversations/read-all');
  }

  /// POST /conversations/{conversation_id}/messages/{message_id}/stick — Stick Conversation Message
  ///
  /// Stick a message in a conversation. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [messageId] Id of message.
  Future<Map<String, dynamic>> conversationsMessagesStick({
    required int conversationId,
    required int messageId,
  }) {
    return post('/conversations/$conversationId/messages/$messageId/stick');
  }

  /// DELETE /conversations/{conversation_id}/messages/{message_id}/stick — Unstick Conversation Message
  ///
  /// Unstick a message in a conversation. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  ///
  /// [messageId] Id of message.
  Future<Map<String, dynamic>> conversationsMessagesUnstick({
    required int conversationId,
    required int messageId,
  }) {
    return delete('/conversations/$conversationId/messages/$messageId/stick');
  }

  /// POST /conversations/{conversation_id}/star — Star Conversation
  ///
  /// Star conversation. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  Future<Map<String, dynamic>> conversationsStar({
    required int conversationId,
  }) {
    return post('/conversations/$conversationId/star');
  }

  /// DELETE /conversations/{conversation_id}/star — Unstar Conversation
  ///
  /// Unstar conversation. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  Future<Map<String, dynamic>> conversationsUnstar({
    required int conversationId,
  }) {
    return delete('/conversations/$conversationId/star');
  }

  /// POST /conversations/{conversation_id}/alerts — Enable Conversation Alerts
  ///
  /// Enable alerts for conversation. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  Future<Map<String, dynamic>> conversationsAlertsEnable({
    required int conversationId,
  }) {
    return post('/conversations/$conversationId/alerts');
  }

  /// DELETE /conversations/{conversation_id}/alerts — Disable Conversation Alerts
  ///
  /// Disable alerts for conversation. Required scopes: + **post** + **conversate**
  ///
  /// [conversationId] Id of conversation.
  Future<Map<String, dynamic>> conversationsAlertsDisable({
    required int conversationId,
  }) {
    return delete('/conversations/$conversationId/alerts');
  }

  /// GET /notifications — Get Notifications
  ///
  /// List of notifications (both read and unread). Required scopes: + **read**
  ///
  /// [type] Filter notifications by their type.
  ///
  /// [page] Page number of notifications.
  ///
  /// [limit] Number of notifications in a page.
  Future<Map<String, dynamic>> notificationsList({
    String? type,
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (type != null) 'type': type!,
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/notifications', params: _queryArgs);
  }

  /// GET /notifications/{notification_id}/content — Get Notification
  ///
  /// Get associated content of notification. The response depends on the content type.
  /// Required scopes: + **read**
  ///
  /// [notificationId] Id of notification.
  Future<Map<String, dynamic>> notificationsGet({
    required int notificationId,
  }) {
    return get('/notifications/$notificationId/content');
  }

  /// POST /notifications/read — Mark Notification Read
  ///
  /// Mark single notification or all existing notifications read. Required scopes: + **post**
  ///
  /// [notificationId] If notification_id is omitted, it's mark all existing notifications as read.
  Future<Map<String, dynamic>> notificationsRead({
    int? notificationId,
  }) {
    final bodyMap = <String, dynamic>{
        if (notificationId != null) 'notification_id': notificationId,
    };
    return post('/notifications/read', body: bodyMap);
  }

  /// GET /tags — Get Popular Tags
  ///
  /// List of popular tags (no pagination). Required scopes: + **read**
  Future<Map<String, dynamic>> tagsPopular() {
    return get('/tags');
  }

  /// GET /tags/list — Get Tags
  ///
  /// List of tags. Required scopes: + **read**
  ///
  /// [page] Page number of tags list.
  ///
  /// [limit] Number of results in a page.
  Future<Map<String, dynamic>> tagsList({
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/tags/list', params: _queryArgs);
  }

  /// GET /tags/{tag_id} — Get Tagged Content
  ///
  /// List of tagged contents. Required scopes: + **read**
  ///
  /// [tagId] Id of tag.
  ///
  /// [page] Page number of tagged contents.
  ///
  /// [limit] Number of tagged contents in a page.
  Future<Map<String, dynamic>> tagsGet({
    required int tagId,
    int? page,
    int? limit,
  }) {
    final _queryArgs = <String, String>{
      if (page != null) 'page': page!.toString(),
      if (limit != null) 'limit': limit!.toString(),
    };
    return get('/tags/$tagId', params: _queryArgs);
  }

  /// GET /tags/find — Get Filtered Content
  ///
  /// Filtered list of tags. Required scopes: + **read**
  ///
  /// [tag] tag to filter. Tags start with the query will be returned.
  Future<Map<String, dynamic>> tagsFind({
    required String tag,
  }) {
    final _queryArgs = <String, String>{
      'tag': tag,
    };
    return get('/tags/find', params: _queryArgs);
  }

  /// POST /search — Search
  ///
  /// Search for all supported contents. Required scopes: + **post**
  ///
  /// [q] Search query. Can be skipped if **user_id** is set.
  ///
  /// [tag] Tag to search for tagged contents.
  ///
  /// [forumId] Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
  ///
  /// [page] Page number of results.
  ///
  /// [limit] Number of results in a page.
  Future<Map<String, dynamic>> searchAll({
    String? q,
    String? tag,
    int? forumId,
    String? userId,
    int? page,
    int? limit,
  }) {
    final bodyMap = <String, dynamic>{
        if (q != null) 'q': q,
        if (tag != null) 'tag': tag,
        if (forumId != null) 'forum_id': forumId,
        if (userId != null) 'user_id': userId,
        if (page != null) 'page': page,
        if (limit != null) 'limit': limit,
    };
    return post('/search', body: bodyMap);
  }

  /// POST /search/threads — Search Thread
  ///
  /// Search for threads. Required scopes: + **post**
  ///
  /// [q] Search query. Can be skipped if **user_id** is set.
  ///
  /// [tag] Tag to search for tagged contents.
  ///
  /// [forumId] Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
  ///
  /// [page] Page number of results.
  ///
  /// [limit] Number of results in a page.
  ///
  /// [dataLimit] Number of thread data to be returned.
  Future<Map<String, dynamic>> searchThreads({
    String? q,
    String? tag,
    int? forumId,
    String? userId,
    int? page,
    int? limit,
    int? dataLimit,
  }) {
    final bodyMap = <String, dynamic>{
        if (q != null) 'q': q,
        if (tag != null) 'tag': tag,
        if (forumId != null) 'forum_id': forumId,
        if (userId != null) 'user_id': userId,
        if (page != null) 'page': page,
        if (limit != null) 'limit': limit,
        if (dataLimit != null) 'data_limit': dataLimit,
    };
    return post('/search/threads', body: bodyMap);
  }

  /// POST /search/posts — Search Post
  ///
  /// Search for posts. Required scopes: + **post**
  ///
  /// [q] Search query. Can be skipped if **user_id** is set.
  ///
  /// [tag] Tag to search for tagged contents.
  ///
  /// [forumId] Id of the container forum to search for contents. Child forums of the specified forum will be included in the search.
  ///
  /// [page] Page number of results.
  ///
  /// [limit] Number of results in a page.
  ///
  /// [dataLimit] Number of post data to be returned.
  Future<Map<String, dynamic>> searchPosts({
    String? q,
    String? tag,
    int? forumId,
    String? userId,
    int? page,
    int? limit,
    int? dataLimit,
  }) {
    final bodyMap = <String, dynamic>{
        if (q != null) 'q': q,
        if (tag != null) 'tag': tag,
        if (forumId != null) 'forum_id': forumId,
        if (userId != null) 'user_id': userId,
        if (page != null) 'page': page,
        if (limit != null) 'limit': limit,
        if (dataLimit != null) 'data_limit': dataLimit,
    };
    return post('/search/posts', body: bodyMap);
  }

  /// POST /search/users — Search Users
  ///
  /// Search for users. Required scopes: + **post**
  ///
  /// [q] Search query.
  Future<Map<String, dynamic>> searchUsers({
    String? q,
  }) {
    final bodyMap = <String, dynamic>{
        if (q != null) 'q': q,
    };
    return post('/search/users', body: bodyMap);
  }

  /// POST /search/profile-posts — Search Profile Posts
  ///
  /// Search for profile posts. Required scopes: + **post**
  ///
  /// [q] Search query. Can be skipped if **user_id** is set.
  ///
  /// [userId] User ID to filter profile posts.
  ///
  /// [page] Page number of results.
  ///
  /// [limit] Number of results in a page.
  Future<Map<String, dynamic>> searchProfileposts({
    String? q,
    int? userId,
    int? page,
    int? limit,
  }) {
    final bodyMap = <String, dynamic>{
        if (q != null) 'q': q,
        if (userId != null) 'user_id': userId,
        if (page != null) 'page': page,
        if (limit != null) 'limit': limit,
    };
    return post('/search/profile-posts', body: bodyMap);
  }

  /// POST /search/tagged — Search Tagged
  ///
  /// Search for tagged contents. Required scopes: + **post**
  ///
  /// [tag] Tag to search for tagged contents.
  ///
  /// [tags] Array of tags to search for tagged contents.
  ///
  /// [page] Page number of results.
  ///
  /// [limit] Number of results in a page.
  Future<Map<String, dynamic>> searchTagged({
    String? tag,
    List<String>? tags,
    int? page,
    int? limit,
  }) {
    final bodyMap = <String, dynamic>{
        if (tag != null) 'tag': tag,
        if (tags != null) 'tags': tags,
        if (page != null) 'page': page,
        if (limit != null) 'limit': limit,
    };
    return post('/search/tagged', body: bodyMap);
  }

  /// GET /search/{search_id}/results — Get Search Results
  ///
  /// List of search results (with pagination). Required scopes: + **get**
  ///
  /// [searchId] Search ID.
  Future<Map<String, dynamic>> searchResults({
    required String searchId,
  }) {
    return get('/search/$searchId/results');
  }

  /// POST /batch — Batch
  ///
  /// Execute multiple API requests at once (Separated by comma). Maximum batch jobs is 10.
  /// Required scopes: + Same as called API requests.
  Future<Map<String, dynamic>> batchExecute({
    Map<String, dynamic>? body,
  }) {
    return post('/batch', body: body);
  }

  /// GET /chatbox — Get Chats
  ///
  /// Get chat rooms. Required scopes: + **chatbox**
  ///
  /// [roomId] Room id.
  Future<Map<String, dynamic>> chatboxIndex({
    int? roomId,
  }) {
    final _queryArgs = <String, String>{
      if (roomId != null) 'room_id': roomId!.toString(),
    };
    return get('/chatbox', params: _queryArgs);
  }

  /// GET /chatbox/messages — Get Chat Messages
  ///
  /// Get chat messages. Required scopes: + **chatbox**
  ///
  /// [roomId] Room id.
  ///
  /// [beforeMessageId] Message id to get older chat messages.
  Future<Map<String, dynamic>> chatboxGetmessages({
    required int roomId,
    int? beforeMessageId,
  }) {
    final _queryArgs = <String, String>{
      'room_id': roomId.toString(),
      if (beforeMessageId != null) 'before_message_id': beforeMessageId!.toString(),
    };
    return get('/chatbox/messages', params: _queryArgs);
  }

  /// POST /chatbox/messages — Create Chat Message
  ///
  /// Create chat message. Required scopes: + **chatbox**
  ///
  /// [replyMessageId] ID of the message being replied to.
  ///
  /// [message] Content of the chat message.
  Future<Map<String, dynamic>> chatboxPostmessage({
    required int roomId,
    required String message,
    int? replyMessageId,
  }) {
    final bodyMap = <String, dynamic>{
        'room_id': roomId,
        if (replyMessageId != null) 'reply_message_id': replyMessageId,
        'message': message,
    };
    return post('/chatbox/messages', body: bodyMap);
  }

  /// PUT /chatbox/messages — Edit Chat Message
  ///
  /// Edit chat message. Required scopes: + **chatbox**
  ///
  /// [messageId] Message id.
  ///
  /// [message] New content of the chat message.
  Future<Map<String, dynamic>> chatboxEditmessage({
    required int messageId,
    required String message,
  }) {
    final bodyMap = <String, dynamic>{
        'message_id': messageId,
        'message': message,
    };
    return put('/chatbox/messages', body: bodyMap);
  }

  /// DELETE /chatbox/messages — Delete Chat Message
  ///
  /// Delete chat message. Required scopes: + **chatbox**
  Future<Map<String, dynamic>> chatboxDeletemessage() {
    return delete('/chatbox/messages');
  }

  /// GET /chatbox/messages/online — Get Chat Online
  ///
  /// Get chat Online Users. Required scopes: + **chatbox**
  ///
  /// [roomId] Room id.
  Future<Map<String, dynamic>> chatboxOnline({
    required int roomId,
  }) {
    final _queryArgs = <String, String>{
      'room_id': roomId.toString(),
    };
    return get('/chatbox/messages/online', params: _queryArgs);
  }

  /// GET /chatbox/messages/report — Get Chat Message Report Reasons
  ///
  /// Report chat message. Required scopes: + **chatbox**
  ///
  /// [messageId] Message id.
  Future<Map<String, dynamic>> chatboxReportreasons({
    required int messageId,
  }) {
    final _queryArgs = <String, String>{
      'message_id': messageId.toString(),
    };
    return get('/chatbox/messages/report', params: _queryArgs);
  }

  /// POST /chatbox/messages/report — Report Chat Message
  ///
  /// Report chat message. Required scopes: + **chatbox**
  ///
  /// [messageId] Message id.
  ///
  /// [reason] Report reason.
  Future<Map<String, dynamic>> chatboxReport({
    required int messageId,
    required String reason,
  }) {
    final bodyMap = <String, dynamic>{
        'message_id': messageId,
        'reason': reason,
    };
    return post('/chatbox/messages/report', body: bodyMap);
  }

  /// GET /chatbox/messages/leaderboard — Get Chat Leaderboard
  ///
  /// Get chat leaderboard. Required scopes: + **chatbox**
  ///
  /// [duration] Duration.
  Future<Map<String, dynamic>> chatboxGetleaderboard({
    String? duration,
  }) {
    final _queryArgs = <String, String>{
      if (duration != null) 'duration': duration!,
    };
    return get('/chatbox/messages/leaderboard', params: _queryArgs);
  }

  /// GET /chatbox/ignore — Get Ignored Chat Users
  ///
  /// Get list of ignored chat users. Required scopes: + **chatbox**
  Future<Map<String, dynamic>> chatboxGetignore() {
    return get('/chatbox/ignore');
  }

  /// POST /chatbox/ignore — Ignore Chat User
  ///
  /// Ignore chat user. Required scopes: + **chatbox**
  Future<Map<String, dynamic>> chatboxPostignore({
    required String userId,
  }) {
    final bodyMap = <String, dynamic>{
        'user_id': userId,
    };
    return post('/chatbox/ignore', body: bodyMap);
  }

  /// DELETE /chatbox/ignore — Unignore Chat User
  ///
  /// Unignore chat user. Required scopes: + **chatbox**
  Future<Map<String, dynamic>> chatboxDeleteignore() {
    return delete('/chatbox/ignore');
  }

  /// GET /forms — Get Forms List
  ///
  /// Get Forms List
  ///
  /// [page] Page number of forms.
  Future<Map<String, dynamic>> formsList({
    int? page,
  }) {
    final _queryArgs = <String, String>{
      if (page != null) 'page': page!.toString(),
    };
    return get('/forms', params: _queryArgs);
  }

  /// POST /forms/save — Create Form
  ///
  /// Create Form.
  Future<Map<String, dynamic>> formsCreate({
    Map<String, dynamic>? body,
  }) {
    return post('/forms/save', body: body);
  }
}
